name: Build

on: [push]
jobs:
  build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - run: New-Item -Path .\_public -Type Directory
    - name: Build Documentation
      run: |
        choco install docfx -y
        docfx .\Docs\docfx.json
        Move-Item -Path .\Docs\doc -Destination .\_public
    - name: Build Demo
      run: |
        (Get-Content -Path .\Demos\DemoBlazorApp\wwwroot\index.html) -replace '<base href="/" />', '<base href="/VisualProgrammer/wasm-demo/" />' | Set-Content -Path .\Demos\DemoBlazorApp\wwwroot\index.html
        dotnet restore
        dotnet publish --configuration Release --output demo-build
        Rename-Item .\demo-build\DemoBlazorApp\dist wasm-demo
        Move-Item -Path .\demo-build\DemoBlazorApp\wasm-demo -Destination .\_public
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: _public
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
